"""
Placeholder
===========

This demonstrates how to use the tools for reading SDFs generated by TSUNAMI-3D.
"""
from tsunami_ip_utils.readers import RegionIntegratedSdfReader

model_1 = RegionIntegratedSdfReader('sphere_model_1.sdf')
model_1.convert_to_dict()
print(model_1.sdf_data['u-235'].keys())