jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/is_rsa
          ssh-keyscan gitlab.gitlab-matthew-louis-code.com >> ~/.ssh/known_hosts

      - name: Clone GitLab repository
        run: git clone --branch gh-pages git@gitlab.gitlab-matthew-louis-code.com:root/tsunami_ip_utils.git gitlab-repo

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact from 'docs' folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: './gitlab-repo/docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4